spring.application.name=NOTIFICATION-SERVICEE

server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true