spring.application.name=eureka-server
#standard port number
server.port=8761

#eureka server won't register itself 
eureka.client.register-with-eureka=false

#won't fetch its own registry
eureka.client.fetch-registry=false

#starts immediately, no wait
eureka.server.wait-time-in-ms-when-sync-empty=0
